import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import BarItem from "@/components/bar-item";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const lineNum = []
   for (let index = 1; index < 27; index++) {
      lineNum.push(<><span>{index}</span> <br /></>)

   }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar></Sidebar>
        <div className=" pl-3 sm:ml-64 bg-gray-50 h-screen overflow-hidden">
            <BarItem>index.js</BarItem>
            <div className="absolute p-0 font-light text-slate-400 text-right select-none overflow-hidden">
               {lineNum}
            </div>
            <div className="p-4 dark:border-gray-700 overflow-hidden h-screen">
              {children}
            </div>
          </div>
      </body>
    </html>
  );
}
